<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * Auto-generated by installer. Do not commit secrets.
 * This file is included by your CI database.php or other bootstrap.
 */
$config['app_base_url'] = 'https://hrm.rcmcentric.com/';

$config['db'] = [
    'hostname' => 'localhost',
    'username' => 'u993957070_teamhrm',
    'password' => 'E1!b5XR&Yf',
    'database' => 'u993957070_teamhrm',
    'dbdriver' => 'mysqli',
    'dbprefix' => '',
    'pconnect' => FALSE,
    'db_debug' => (ENVIRONMENT !== 'production'),
    'cache_on' => FALSE,
    'cachedir' => '',
    'char_set' => 'utf8mb4',
    'dbcollat' => 'utf8mb4_unicode_ci',
    'swap_pre' => '',
    'encrypt'  => FALSE,
    'compress' => FALSE,
    'stricton' => FALSE,
    'failover' => [],
    'save_queries' => TRUE
];
